version: "3.4"

networks:
  app:
    driver: bridge

services:
  users_service:
    build:
      context: .
      dockerfile: ./build/Dockerfile_users_service
    restart: always
    container_name: 'users_service'
    ports:
      - 8081:8080
      - 8082:8082
    networks:
      - app
  friends_service:
    build:
      context: .
      dockerfile: ./build/Dockerfile_friends_service
    restart: always
    environment:
      - USERS_SERVICE=users_service
      - USER_SERVICE_GRPC_PORT=8082
    container_name: 'friends_service'
    ports:
      - 8085:8080
      - 8086:8082
    networks:
      - app
  chat_service:
    build:
      context: .
      dockerfile: ./build/Dockerfile_chat_service
    restart: always
    environment:
      - USERS_SERVICE=users_service
      - USER_SERVICE_GRPC_PORT=8082
      - FRIENDS_SERVICE=friends_service
      - FRIENDS_SERVICE_GRPC_PORT=8086
    container_name: 'chat_service'
    ports:
      - 8088:8080
      - 8089:8082
    networks:
      - app      
  